### ISSUE TITLE
remove stdio.h from stack.h

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/bf_interpreter_jit_compiler#2]

**Comment by nickdesaulniers** [comment]
needed for size_t

**Comment by rdebath** [comment]
Technically, the correct header for size_t is &lt;stddef.h>, it also appears in &lt;stdio.h> because it's used by fread and fwrite.

**Comment by nickdesaulniers** [comment]
What's the best way to look this information up?  man pages don't work for typedefs...

**Comment by rdebath** [comment]
I'd guess the POSIX/XOPEN standards themselves, they give you what's supposed to be in each file with references that say "as described in xyz.h". Not that it really matters that much though.

[for POSIX 1997](http://pubs.opengroup.org/onlinepubs/7908799/headix.html)
[for POSIX 2003](http://pubs.opengroup.org/onlinepubs/007904975/)
[for POSIX 2013](http://pubs.opengroup.org/onlinepubs/9699919799/)

**Comment by nickdesaulniers** [comment]
oh, I was curious how C/C++ devs know this.  Reading the spec isn't as practical as a tool like man pages (for example how they tell you what header you need to include for which function).  Oh well.
